export const siteConfig = {
  name: "Harry's Happy Vending",
  shortName: "Harry's Happy",
  url: "https://www.harryshappy.com",
  phone: "905-332-3925",
  phoneHref: "tel:+19053323925",
  email: "info@harryshappy.com",
  hours: "Mon–Fri, 8:00 AM–5:00 PM",
  foundedYear: 2006,
  yearsInBusiness: new Date().getFullYear() - 2006,
  locationsServed: "300+",
  region: "the Golden Horseshoe",
  tagline: "Reliable Vending for Ontario Workplaces",
  description:
    "Family-owned since 2006, Harry's Happy Vending helps factories, warehouses, and workplaces create better break rooms with customized vending, coffee service, fresh food, and micro markets—backed by dependable local service.",
  social: {
    linkedin: null as string | null,
  },
  serviceAreaCities: [
    "Hamilton",
    "Stoney Creek",
    "Burlington",
    "Milton",
    "Oakville",
    "Etobicoke",
    "Mississauga",
    "Brampton",
  ],
  priorityCities: ["Hamilton", "Burlington", "Milton", "Oakville", "Stoney Creek"],
};
